-- Migration 002: Alert engine tables
-- Depends on: 001_init.sql (asset_metadata must exist)
-- Used by: services/alerting (Phase 2), services/api (Phase 3)

-- ─── ALERT RULES ─────────────────────────────────────────────────────────────
-- Operator-configurable threshold rules per (asset, signal) pair.
-- The alerting service polls this table every 60s via RuleLoader.

CREATE TABLE IF NOT EXISTS alert_rules (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  asset        TEXT        NOT NULL,
  signal       TEXT        NOT NULL,
  -- Warning band: fires 'warning' severity alert
  warn_low     DOUBLE PRECISION,
  warn_high    DOUBLE PRECISION,
  -- Critical band: fires 'critical' severity alert (overrides warning)
  crit_low     DOUBLE PRECISION,
  crit_high    DOUBLE PRECISION,
  enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (asset, signal)
);

-- Seed default rules for the 4 demo assets (matches register_map.json ranges)
INSERT INTO alert_rules (asset, signal, warn_low, warn_high, crit_low, crit_high)
VALUES
  -- Feeder: monitor feed_rate and motor_temp
  ('feeder-01',   'feed_rate',    2.0,   NULL,  1.0,  NULL),
  ('feeder-01',   'motor_temp',   NULL,  75.0,  NULL, 90.0),
  -- Mixer: monitor rpm and torque
  ('mixer-01',    'rpm',          10.0,  NULL,  5.0,  NULL),
  ('mixer-01',    'torque_pct',   NULL,  85.0,  NULL, 95.0),
  -- Conveyor: monitor belt_speed and vibration
  ('conveyor-01', 'belt_speed',   0.2,   NULL,  0.1,  NULL),
  ('conveyor-01', 'vibration',    NULL,  6.0,   NULL, 9.0),
  -- Packer: monitor cycle_time and reject_count
  ('packer-01',   'cycle_time',   NULL,  5.0,   NULL, 8.0),
  ('packer-01',   'reject_count', NULL,  10.0,  NULL, 20.0)
ON CONFLICT (asset, signal) DO NOTHING;

-- ─── ALERTS ──────────────────────────────────────────────────────────────────
-- TimescaleDB hypertable — partitioned on opened_at so time-range queries
-- (e.g. "alerts from the last 8 hours") stay fast as history accumulates.
--
-- State machine:
--   OPEN  →  ACKED   (operator acknowledged via POST /api/v1/alerts/{id}/acknowledge)
--   OPEN  →  CLOSED  (auto-closed by router when condition resolves)
--   ACKED →  CLOSED  (auto-closed by router when condition resolves)

CREATE TABLE IF NOT EXISTS alerts (
  id           UUID        NOT NULL DEFAULT gen_random_uuid(),
  opened_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  site         TEXT        NOT NULL,
  line_name    TEXT        NOT NULL,
  asset        TEXT        NOT NULL,
  signal       TEXT        NOT NULL,
  -- Which detection layer fired: threshold | statistical | ml
  alert_type   TEXT        NOT NULL CHECK (alert_type IN ('threshold', 'statistical', 'ml')),
  -- Severity inherited from the rule or computed by the detection layer
  severity     TEXT        NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
  -- The raw sensor value that triggered the alert
  value        DOUBLE PRECISION NOT NULL,
  -- The threshold that was crossed (NULL for statistical/ml alerts)
  threshold    DOUBLE PRECISION,
  -- Human-readable description generated by the detector
  message      TEXT        NOT NULL,
  -- State machine column
  state        TEXT        NOT NULL DEFAULT 'OPEN' CHECK (state IN ('OPEN', 'ACKED', 'CLOSED')),
  acked_at     TIMESTAMPTZ,
  closed_at    TIMESTAMPTZ,
  -- FK to the rule that triggered this alert (NULL for statistical/ml)
  rule_id      UUID        REFERENCES alert_rules(id),
  PRIMARY KEY (opened_at, id)
);

SELECT create_hypertable('alerts', 'opened_at', if_not_exists => TRUE);

-- Fast lookups for "all open alerts for an asset" and "recent alert history"
CREATE INDEX IF NOT EXISTS alerts_asset_state_idx
  ON alerts (asset, state, opened_at DESC);

CREATE INDEX IF NOT EXISTS alerts_state_opened_idx
  ON alerts (state, opened_at DESC);
