apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-collector
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  replicas: {{ .Values.collector.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" (dict "root" . "component" "collector") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" (dict "root" . "component" "collector") | nindent 8 }}
    spec:
      containers:
        - name: collector
          image: {{ include "nexus.image" (dict "root" . "repo" .Values.collector.image.repository) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- include "nexus.commonEnv" . | nindent 12 }}
            - name: MODBUS_HOST
              value: {{ .Release.Name }}-modbus-sim
            - name: MODBUS_PORT
              value: "1502"
            - name: SITE
              value: {{ .Values.collector.env.SITE | quote }}
            - name: LINE
              value: {{ .Values.collector.env.LINE | quote }}
            - name: COLLECT_INTERVAL_MS
              value: {{ .Values.collector.env.COLLECT_INTERVAL_MS | quote }}
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
