apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ingestor
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestor
spec:
  replicas: {{ .Values.ingestor.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" (dict "root" . "component" "ingestor") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" (dict "root" . "component" "ingestor") | nindent 8 }}
    spec:
      containers:
        - name: ingestor
          image: {{ include "nexus.image" (dict "root" . "repo" .Values.ingestor.image.repository) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- include "nexus.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.ingestor.resources | nindent 12 }}
