apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresPassword: {{ .Values.secrets.postgresPassword | quote }}
  mqttPassword: {{ .Values.secrets.mqttPassword | quote }}
  apiKey: {{ .Values.secrets.apiKey | quote }}
  grafanaAdminPassword: {{ .Values.secrets.grafanaAdminPassword | quote }}
